### ISSUE TITLE
Instructions for updating biblatex

### ISSUE THREAD

**Issue by madaalch** [anoduck/Biber-OpenBSD#3]
Biber needs a compatible version of biblatex to function correctly.
I'm using package texlive_mf-full-2022 which contains an incompatible version of biblatex,
and compiling with pdflatex.

Below is some md that you may want to add to the README to help others in a similar situation

-----
```
### BibLaTeX
In order for biber to work, it needs a compatible version of BibLaTeX.
Once you have verified that biber is functioning and have copied it to the bin directory of your choice run `biber --version` and make note.

To find the compatible version, visit the [biber documentation page](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/documentation) and in biber.pdf look at compatibility matrix.
Download the corresponding version of BibLaTeX from [sourceforge](https://sourceforge.net/projects/biblatex)

Run `kpsewhich -var-value=TEXHOME` and make note of directory;
(it should be `~/texmf`; if this doesn't exist then create it).
`cd` to directory which contains the downloaded biblatex-*.tgz.
`tar -zxvf biblatex-*.tgz -C ~/texmf` where * is the version you have just downloaded.
`texhash ~/texmf`

*NOTE* after running the above command, `kpsewhich -var-value=TEXHOME` will no longer print anything.

> NOTE TO ANODUCK; I think you could make the texmf directory anywhere and run `texhash` with the appropriate directory, however I wanted to play things by the book. If you're more confident about the safety of this then you could recommend a different place. I personally can't stand cluttering up my home directory.)

Now go back to the `~/Sandbox/biber/testfiles` directory and `pdflatex test ; biber test ; pdflatex test`.
Open the test.pdf; if you have no errors then your test.pdf will list a single successful reference.

Back up the document that you wish to run biber with.
Run `pdflatex yourdocumentname ; biber yourdocumentname` and check for errors.
Note that if your .bib file's name contains 12 or more characters you will get an error,
(example bibliography.bib will be truncated to bibliograph.bib, which biber will not be able to find.)
if needs be rename it to biblio.bib or something similarly short.
Now recompile your document and you should have all your beautiful references sorted.
```

**Comment by anoduck** [comment]
@madaalch Make a pull request, that way it shows you are a contributor to the repo, and you get credit. You deserve the credit.

Just because I do not know if you have ever performed a pull request before, here is how to do it. Super easy. 
1. Fork the repo.
2. Clone your fork. `git clone https://github.com…`
3. Modify your clone.
4. Commit and push back to your fork. `git add . && git commit -am 'my message' && git push`
5. Click create pull request on your forked repo.
6. Add a message and click submit.

**Comment by madaalch** [comment]
Thanks, will do that when I have the time.

**Comment by anoduck** [comment]
@madaalch Seriously, it should take you all of fifteen minutes to fork, clone, copy & paste, commit, push, and submit a PR. It will probably take me more time to write this response, than for you to submit a PR.

**Comment by anoduck** [comment]
@madaalch Since I solved the mystery of installing biber on OpenBSD, and dedicated quite a significant amount of time to write up a tutorial solely to aid your success in duplicating this accomplishment. Could you help me troubleshoot why vmm does not provide network connectivity to my virtual machines?

My IP is configured statically on a bridge interface. I am just unsure if vmm takes after docker and handles the firewall portion for you, or whether rules need to be added to PF to allow connectivity?

**Comment by madaalch** [comment]
Yes you'll have to config PF https://www.openbsd.org/faq/faq16.html#VMMnet
I'm sure this should be enough but let me know if there are still problems. I'll get you mt email address or whatever other way you want to communicate if that's better for you than github

**Comment by anoduck** [comment]
@madaalch Yeah, I feel like an idiot now. Creating vether0 and adding it to my bridge would definitely be the clincher. 

I use protonmail.

**Comment by madaalch** [comment]
Been busy with all sorts of stuff, sorry for the late reply. You'll find my email address in my private repo, under issue email
