### ISSUE TITLE
Removing perlbrew

### ISSUE THREAD

**Issue by madaalch** [anoduck/Biber-OpenBSD#4]
I had a look at the compiled biber, and ran some checks on it:
`objdump -p biber` and `ldd biber` in my `~/bin/` showed that all the shared libraries for the binary are in /usr/lib{exec}, none in the directory I kept perlbrew in.

I moved the perlbrew installation to a USB stick then removed it, and afterwards biber seems to function just fine.

It seems like your method of making biber is a standalone binary.

I'm planning on making a more thorough test of biber's functionality without perlbrew and will let you know if there are any issues.
Would you like to verify this yourself?

**Comment by anoduck** [comment]
How about them marbles! So, it is. 

I did test running biber from `/usr/local/bin/biber` previously, and it failed to run the tests, but now whatever was preventing it from running in that location appears to no longer be an issue. Hmm...interesting...

So, it appears it is safe to move biber to `/usr/local/bin/biber`.

Rather than purge perlbrew from the system, I would just uninstall the perl installation used to compile biber, and disabling perlbrew. `perlbrew uninstall perl-5.38.2 && perlbrew off` This way you can have perlbrew available for subsequent releases of biber and if you ever need to delve into other developmental tidbits of perl.
